{{- if .Values.rbac.create }}
  {{- if and (not .Values.rbac.rules) (not .Values.rbac.clusterRules) }}
    {{- fail "RBAC (Role Based Access Control) rules enabled but no rules provided. Please provide at least one rule in rbac.rules or rbac.clusterRules, or disable RBAC creation." }}
  {{- else if and .Values.rbac.rules (not .Values.rbac.namespaces) }}
    {{- fail "Namespaced RBAC (Role Based Access Control) rules defined without specifying namespaces. Please provide at least one namespace or move the rules to clusterRules." }}
  {{- end }}
  {{- if and .Values.rbac.namespaces .Values.rbac.rules }}
    {{- range $namespace := .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "alloy.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    {{- include "alloy.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  {{- if $.Values.rbac.rules }}
  {{- $.Values.rbac.rules | toYaml | nindent 2 }}
  {{- else }}
  []
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "alloy.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    {{- include "alloy.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "alloy.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alloy.serviceAccountName" $ }}
    namespace: {{ include "alloy.namespace" $ }}
    {{- end }}
  {{- else }}
  {{- if .Values.rbac.clusterRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  {{- if .Values.rbac.clusterRules }}
  {{- .Values.rbac.clusterRules | toYaml | nindent 2 }}
  {{- else }}
  []
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alloy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alloy.serviceAccountName" . }}
    namespace: {{ include "alloy.namespace" . }}
  {{- end }}
  {{- end }}
{{- end }}
